name: ML Model Delpoyment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4
       
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: 3.11

     - name: Install dependencies
       run: pip install -r requirements.txt

     - name: Test with pytest
       run: pytest

     - name: Train and evaluate model
       run: python train.py

     - name: Build Docker image
       run: docker build -t titanic_api .

     - name: Login to DockerHub
       uses: docker/login-action@v3
       with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}
          logout: true

     - name: Push Docker image
       run: docker push hdakhli/api-titanic:latest
